version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: edtech_postgres
    environment:
      POSTGRES_USER: edtech_user
      POSTGRES_PASSWORD: edtech_password
      POSTGRES_DB: edtech_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: edtech_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

volumes:
  postgres_data: